title: Lerntagebuch BAIN Nina
author: Nina
email: nina.ingold@stud.fhgr.ch
description: > # this means to ignore newlines
  Das ist mein Tagebuch über die Lerninhalte des Modules Bibliotheks- und Archivinformatik (BAIN)

# social links
github_username:  Uliqwe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
